// GENERATED BY DEMETRA
// DOES NOT EDIT

package peoples

import "github.com/ihatiko/chef/components/transports/grpc"

const (
	sdkGrpcName = "Grpc.PlanetsService"
)

type PeoplesConfig struct {
	grpc.Config
}

func (p *PeoplesConfig) Name() string {
	return sdkGrpcName
}

func (p *PeoplesConfig) Setup(impl PeoplesServiceServer) grpc.Transport {
	t := p.Config.Use()
	t.Routing(PeoplesService_ServiceDesc, impl)
	return t
}
