// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.0
// 	protoc        v5.29.2
// source: pkg/protoc/planets/planets.proto

package planets

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdatePlanetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePlanetRequest) Reset() {
	*x = UpdatePlanetRequest{}
	mi := &file_pkg_protoc_planets_planets_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePlanetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePlanetRequest) ProtoMessage() {}

func (x *UpdatePlanetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protoc_planets_planets_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePlanetRequest.ProtoReflect.Descriptor instead.
func (*UpdatePlanetRequest) Descriptor() ([]byte, []int) {
	return file_pkg_protoc_planets_planets_proto_rawDescGZIP(), []int{0}
}

type UpdatePlanetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePlanetResponse) Reset() {
	*x = UpdatePlanetResponse{}
	mi := &file_pkg_protoc_planets_planets_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePlanetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePlanetResponse) ProtoMessage() {}

func (x *UpdatePlanetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protoc_planets_planets_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePlanetResponse.ProtoReflect.Descriptor instead.
func (*UpdatePlanetResponse) Descriptor() ([]byte, []int) {
	return file_pkg_protoc_planets_planets_proto_rawDescGZIP(), []int{1}
}

var File_pkg_protoc_planets_planets_proto protoreflect.FileDescriptor

var file_pkg_protoc_planets_planets_proto_rawDesc = []byte{
	0x0a, 0x20, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2f, 0x70, 0x6c, 0x61,
	0x6e, 0x65, 0x74, 0x73, 0x2f, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x07, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x74, 0x73, 0x22, 0x15, 0x0a, 0x13, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x6e, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x16, 0x0a, 0x14, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x6e,
	0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x5f, 0x0a, 0x0e, 0x50, 0x6c,
	0x61, 0x6e, 0x65, 0x74, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4d, 0x0a, 0x0c,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x6e, 0x65, 0x74, 0x12, 0x1c, 0x2e, 0x70,
	0x6c, 0x61, 0x6e, 0x65, 0x74, 0x73, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61,
	0x6e, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x70, 0x6c, 0x61,
	0x6e, 0x65, 0x74, 0x73, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x6e, 0x65,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0b, 0x5a, 0x09, 0x2e,
	0x3b, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x74, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_protoc_planets_planets_proto_rawDescOnce sync.Once
	file_pkg_protoc_planets_planets_proto_rawDescData = file_pkg_protoc_planets_planets_proto_rawDesc
)

func file_pkg_protoc_planets_planets_proto_rawDescGZIP() []byte {
	file_pkg_protoc_planets_planets_proto_rawDescOnce.Do(func() {
		file_pkg_protoc_planets_planets_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_protoc_planets_planets_proto_rawDescData)
	})
	return file_pkg_protoc_planets_planets_proto_rawDescData
}

var file_pkg_protoc_planets_planets_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_protoc_planets_planets_proto_goTypes = []any{
	(*UpdatePlanetRequest)(nil),  // 0: planets.UpdatePlanetRequest
	(*UpdatePlanetResponse)(nil), // 1: planets.UpdatePlanetResponse
}
var file_pkg_protoc_planets_planets_proto_depIdxs = []int32{
	0, // 0: planets.PlanetsService.UpdatePlanet:input_type -> planets.UpdatePlanetRequest
	1, // 1: planets.PlanetsService.UpdatePlanet:output_type -> planets.UpdatePlanetResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_protoc_planets_planets_proto_init() }
func file_pkg_protoc_planets_planets_proto_init() {
	if File_pkg_protoc_planets_planets_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_protoc_planets_planets_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_protoc_planets_planets_proto_goTypes,
		DependencyIndexes: file_pkg_protoc_planets_planets_proto_depIdxs,
		MessageInfos:      file_pkg_protoc_planets_planets_proto_msgTypes,
	}.Build()
	File_pkg_protoc_planets_planets_proto = out.File
	file_pkg_protoc_planets_planets_proto_rawDesc = nil
	file_pkg_protoc_planets_planets_proto_goTypes = nil
	file_pkg_protoc_planets_planets_proto_depIdxs = nil
}
