// GENERATED BY DEMETRA
// DOES NOT EDIT

package planets

import "github.com/ihatiko/chef/components/transports/grpc"

const (
	sdkGrpcName = "Grpc.PlanetsService"
)

type PlanetsConfig struct {
	grpc.Config
}

func (p *PlanetsConfig) Name() string {
	return sdkGrpcName
}

func (p *PlanetsConfig) Setup(impl PlanetsServiceServer) grpc.Transport {
	t := p.Use()
	t.Routing(PlanetsService_ServiceDesc, impl)
	return t
}
