// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.2
// source: pkg/protoc/planets/planets.proto

package planets

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PlanetsService_UpdatePlanet_FullMethodName = "/planets.PlanetsService/UpdatePlanet"
)

// PlanetsServiceClient is the client API for PlanetsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PlanetsServiceClient interface {
	UpdatePlanet(ctx context.Context, in *UpdatePlanetRequest, opts ...grpc.CallOption) (*UpdatePlanetResponse, error)
}

type planetsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPlanetsServiceClient(cc grpc.ClientConnInterface) PlanetsServiceClient {
	return &planetsServiceClient{cc}
}

func (c *planetsServiceClient) UpdatePlanet(ctx context.Context, in *UpdatePlanetRequest, opts ...grpc.CallOption) (*UpdatePlanetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdatePlanetResponse)
	err := c.cc.Invoke(ctx, PlanetsService_UpdatePlanet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlanetsServiceServer is the server API for PlanetsService service.
// All implementations should embed UnimplementedPlanetsServiceServer
// for forward compatibility.
type PlanetsServiceServer interface {
	UpdatePlanet(context.Context, *UpdatePlanetRequest) (*UpdatePlanetResponse, error)
}

// UnimplementedPlanetsServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPlanetsServiceServer struct{}

func (UnimplementedPlanetsServiceServer) UpdatePlanet(context.Context, *UpdatePlanetRequest) (*UpdatePlanetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePlanet not implemented")
}
func (UnimplementedPlanetsServiceServer) testEmbeddedByValue() {}

// UnsafePlanetsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PlanetsServiceServer will
// result in compilation errors.
type UnsafePlanetsServiceServer interface {
	mustEmbedUnimplementedPlanetsServiceServer()
}

func RegisterPlanetsServiceServer(s grpc.ServiceRegistrar, srv PlanetsServiceServer) {
	// If the following call pancis, it indicates UnimplementedPlanetsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PlanetsService_ServiceDesc, srv)
}

func _PlanetsService_UpdatePlanet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePlanetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlanetsServiceServer).UpdatePlanet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlanetsService_UpdatePlanet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlanetsServiceServer).UpdatePlanet(ctx, req.(*UpdatePlanetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PlanetsService_ServiceDesc is the grpc.ServiceDesc for PlanetsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PlanetsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "planets.PlanetsService",
	HandlerType: (*PlanetsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdatePlanet",
			Handler:    _PlanetsService_UpdatePlanet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/protoc/planets/planets.proto",
}
